// src/components/FriendCard.vue
<script setup lang="ts">
import "tippy.js/animations/shift-away.css";
import "tippy.js/animations/shift-away-subtle.css";

import { h, ref, onMounted } from "vue";
import { useTippy } from "vue-tippy";
import { useRobloxApi } from "../utils/robloxApi";

import FriendTooltip from "./FriendTooltip.vue";

import {
    FriendUserInformation,
    UserPresence,
    PlaceDetails,
    ThumbnailSize,
    ThumbnailType
} from "../utils/typings.ts";

const robloxApi = useRobloxApi();
const props = defineProps<{
    headshot: string;
    friend: FriendUserInformation;
    friendPresence: UserPresence;
}>();

const btn = ref();

const tooltip = useTippy(btn, {
    content: "",
    placement: "bottom",

    interactive: true,
    duration: [0, 100],
    animateFill: true,
});

onMounted(async () => {
    console.log(props);
    let placeDetails: PlaceDetails | undefined;
    let placeThumbnail: string = "https://placehold.co/512";
    if (
        props.friendPresence.presence_type === "InGame" &&
        props.friendPresence.place_id
    ) {
        const currentPlaceDetails = await robloxApi.getPlaceDetails(
            props.friendPresence.place_id
        );

        placeDetails = await robloxApi.getPlaceDetails(
            currentPlaceDetails.universe_root_place_id
        );

        placeThumbnail = await robloxApi
            .getThumbnailsUrls([placeDetails.universe_root_place_id], ThumbnailSize.S768x432, ThumbnailType.GameThumbnail)
            .then((res) => res[0]);
    }

    tooltip.setContent(
        h(FriendTooltip, {
            friend: props.friend,
            friendPresence: props.friendPresence,
            placeDetails,
            placeThumbnail,
        })
    );
});
</script>

<template>
    <div class="friend-card" ref="btn">
        <div class="friend-image">
            <img class="rounded-md" :src="headshot" :alt="props.friend.display_name" width="90" height="90" />

            <span v-if="props.friendPresence.presence_type === 'Online'" class="bg-blue-600 user-status">
                <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                    viewBox="0 0 24 24">
                    <path fill-rule="evenodd"
                        d="M12 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4h-4Z"
                        clip-rule="evenodd" />
                </svg>
            </span>

            <span v-if="props.friendPresence.presence_type === 'InGame'" class="bg-green-600 user-status">
                <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                    viewBox="0 0 24 24">
                    <path fill-rule="evenodd"
                        d="M5 5a2 2 0 0 0-2 2v3a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V7a2 2 0 0 0-2-2H5Zm9 2a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H14Zm3 0a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H17ZM3 17v-3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Zm11-2a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H14Zm3 0a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H17Z"
                        clip-rule="evenodd" />
                </svg>
            </span>

            <span v-if="props.friendPresence.presence_type === 'InStudio'" class="bg-yellow-600 user-status">
                <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                    viewBox="0 0 24 24">
                    <path fill-rule="evenodd"
                        d="M14 4.182A4.136 4.136 0 0 1 16.9 3c1.087 0 2.13.425 2.899 1.182A4.01 4.01 0 0 1 21 7.037c0 1.068-.43 2.092-1.194 2.849L18.5 11.214l-5.8-5.71 1.287-1.31.012-.012Zm-2.717 2.763L6.186 12.13l2.175 2.141 5.063-5.218-2.141-2.108Zm-6.25 6.886-1.98 5.849a.992.992 0 0 0 .245 1.026 1.03 1.03 0 0 0 1.043.242L10.282 19l-5.25-5.168Zm6.954 4.01 5.096-5.186-2.218-2.183-5.063 5.218 2.185 2.15Z"
                        clip-rule="evenodd" />
                </svg>
            </span>
        </div>

        <div class="friend-username">
            <p class="user-name">{{ props.friend.display_name }}</p>
        </div>
    </div>
</template>

<style scoped>
.friend-card {
    --size: 100px;

    @media screen and (max-width: 920px) {
        --size: 80px;
    }

    @apply flex flex-col;

    .friend-image {
        min-width: var(--size);
        min-height: var(--size);

        @apply aspect-square;
        @apply bg-[#787878] rounded-full relative;

        img {
            @apply w-full rounded-full;
        }

        .user-status {
            @apply absolute right-0 bottom-0;
            @apply w-6 h-6 p-0.5;
            @apply text-center;
            @apply rounded-full;

            svg {
                @apply w-full h-full;
            }
        }
    }

    div.friend-username {
        @apply text-xs text-center;
        @apply flex gap-1 justify-center;

        width: var(--size);

        .user-name {
            max-width: calc(var(--size) - 10);
            @apply truncate;
        }

        .user-status {
            @apply w-fit;
        }
    }
}
</style>

// src/lib/components/Cards/FriendCard.svelte
<script lang="ts">
    import "tippy.js/animations/shift-away.css";
    import "tippy.js/animations/shift-away-subtle.css";

    // import FriendTooltip from "./FriendTooltip.vue";

    import type { InternalFriend } from "$lib/typings.ts";

    export let friend: InternalFriend;

    // onMounted(async () => {
    //     console.log(props);
    //     let placeDetails: PlaceDetails | undefined;
    //     let placeThumbnail: string = "https://placehold.co/512";
    //     if (
    //         props.friendPresence.presence_type === "InGame" &&
    //         props.friendPresence.place_id
    //     ) {
    //         const currentPlaceDetails = await robloxApi.getPlaceDetails(
    //             props.friendPresence.place_id
    //         );

    //         placeDetails = await robloxApi.getPlaceDetails(
    //             currentPlaceDetails.universe_root_place_id
    //         );

    //         placeThumbnail = await robloxApi
    //             .getThumbnailsUrls([placeDetails.universe_root_place_id], ThumbnailSize.S768x432, ThumbnailType.GameThumbnail)
    //             .then((res) => res[0]);
    //     }

    //     tooltip.setContent(
    //         h(FriendTooltip, {
    //             friend: props.friend,
    //             friendPresence: props.friendPresence,
    //             placeDetails,
    //             placeThumbnail,
    //         })
    //     );
    // });
</script>

<div class="friend-card">
    <div class="friend-image">
        <img
            class="rounded-md"
            src={friend.headshot}
            alt={friend.info.display_name}
            width="90"
            height="90"
        />

        {#if friend.presence.presence_type === "Online"}
            <span class="bg-blue-600 user-status">
                <svg
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                >
                    <path
                        fill-rule="evenodd"
                        d="M12 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4h-4Z"
                        clip-rule="evenodd"
                    />
                </svg>
            </span>
        {:else if friend.presence.presence_type === "InGame"}
            <span class="bg-green-600 user-status">
                <svg
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                >
                    <path
                        fill-rule="evenodd"
                        d="M5 5a2 2 0 0 0-2 2v3a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V7a2 2 0 0 0-2-2H5Zm9 2a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H14Zm3 0a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H17ZM3 17v-3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Zm11-2a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H14Zm3 0a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H17Z"
                        clip-rule="evenodd"
                    />
                </svg>
            </span>
        {:else if friend.presence.presence_type === "InStudio"}
            <span class="bg-yellow-600 user-status">
                <svg
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                >
                    <path
                        fill-rule="evenodd"
                        d="M14 4.182A4.136 4.136 0 0 1 16.9 3c1.087 0 2.13.425 2.899 1.182A4.01 4.01 0 0 1 21 7.037c0 1.068-.43 2.092-1.194 2.849L18.5 11.214l-5.8-5.71 1.287-1.31.012-.012Zm-2.717 2.763L6.186 12.13l2.175 2.141 5.063-5.218-2.141-2.108Zm-6.25 6.886-1.98 5.849a.992.992 0 0 0 .245 1.026 1.03 1.03 0 0 0 1.043.242L10.282 19l-5.25-5.168Zm6.954 4.01 5.096-5.186-2.218-2.183-5.063 5.218 2.185 2.15Z"
                        clip-rule="evenodd"
                    />
                </svg>
            </span>
        {/if}
    </div>

    <div class="friend-username">
        <p class="user-name">{friend.info.display_name}</p>
    </div>
</div>

<style lang="scss">
    .friend-card {
        --size: 100px;

        @media screen and (max-width: 920px) {
            --size: 80px;
        }

        @apply flex flex-col;

        .friend-image {
            min-width: var(--size);
            min-height: var(--size);

            @apply aspect-square;
            @apply bg-[#787878] rounded-full relative;

            img {
                @apply w-full rounded-full;
            }

            .user-status {
                @apply absolute right-0 bottom-0;
                @apply w-6 h-6 p-0.5;
                @apply text-center;
                @apply rounded-full;

                svg {
                    @apply w-full h-full;
                }
            }
        }

        div.friend-username {
            @apply text-xs text-center;
            @apply flex gap-1 justify-center;

            width: var(--size);

            .user-name {
                max-width: calc(var(--size) - 10);
                @apply truncate;
            }

            .user-status {
                @apply w-fit;
            }
        }
    }
</style>
